### ISSUE TITLE
New model --format=mliap conversion fails

### ISSUE THREAD

**Issue by LucaBrugnoli** [ACEsuit/mace#1165]
Dear MACE team,

I’m converting two new models to the version compatible with LAMMPS and LAMMPS-MLIAP.
I'using the mace development branch.
For the model mace_mh_r2scan_v1.model these worked:

```
# LAMMPS
python3 create_lammps_model.py mace_mh_r2scan_v1.model --head=r2scan
# LAMMPS-MLIAP
python3 create_lammps_model.py mace_mh_r2scan_v1.model --head=r2scan --format=mliap

```
For mace-mh-nl-pbe.model, this worked:

```
# LAMMPS 
python3 create_lammps_model.py mace-mh-nl-pbe.model --head=omat_pbe
```

while this other failed:

```
# LAMMPS-MLIAP 
python3 create_lammps_model.py mace-mh-nl-pbe.model --head=omat_pbe --format=mliap
```

The traceback is :

```
HOME/venvs/mace_developement/lib/python3.12/site-packages/e3nn/o3/_wigner.py:10: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  _Jd, _W3j_flat, _W3j_indices = torch.load(os.path.join(os.path.dirname(__file__), 'constants.pt'))
HOME/MACE_models/mace-mh-nl-pbe/create_lammps_model.py:79: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model = torch.load(
Traceback (most recent call last):
  File "HOME/MACE_models/mace-mh-nl-pbe/create_lammps_model.py", line 114, in <module>
    main()
  File "HOME/MACE_models/mace-mh-nl-pbe/create_lammps_model.py", line 91, in main
    model = run_e3nn_to_cueq(copy.deepcopy(model))
  File "HOME/venvs/mace_developement/lib/python3.12/site-packages/mace/cli/convert_e3nn_cueq.py", line 191, in run
    config = extract_config_mace_model(source_model)
  File "HOME/venvs/mace_developement/lib/python3.12/site-packages/mace/tools/scripts_utils.py", line 312, in extract_config_mace_model
    "radial_MLP": model.interactions[0].conv_tp_weights.hs[1:-1],
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "HOME/venvs/mace_developement/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1931, in __getattr__
    raise AttributeError(
AttributeError: 'RadialMLP' object has no attribute 'hs'
```

Honestly, I don't understand why the pbe model fails at the --format=mliap step while the r2scan model works without issues using the same script and environment.
Could you please help me understand what is going wrong or how I can fix this?
I really need the mliap version to take advantage of parallelization in LAMMPS.

Thanks a lot in advance!

**Comment by angela-oti** [comment]
I also had the same issue when converting the `mace-omol-0-extra-large-4M.model`, so I thought I would add my inputs here.  Additionally, I was able to get the `MACE-omol-0-extra-large-1024.model` to work, but then LAMMPS failed to run (core dumped). I tried several different versions of MACE/development versions/LAMMPS MLIAP. I can also confirm that in my current setup LAMMPS MLIAP does work with other models (including the `mace-omat-0-medium.model`) so my issue appears to be specifically wiht the `mace-omol` models. I also had issues when converting the files using `--format libtorch`. I appreciate you all looking at these errors, and let me know if I can provide any other inputs that might help. Thanks in advance!

-------------

 I am using the `develop` branch of mace with `python==3.10.18` when I run:

```
python -m mace.cli.create_lammps_model mace-omol-0-extra-large-4M.model --format mliap --head omol
```

I get the following error (same as above)

```
Traceback (most recent call last):
  File "HOME/envs/mace-from-git/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "HOME/envs/mace-from-git/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "HOME/envs/mace-from-git/lib/python3.10/site-packages/mace/cli/create_lammps_model.py", line 114, in <module>
    main()
  File "HOME/envs/mace-from-git/lib/python3.10/site-packages/mace/cli/create_lammps_model.py", line 91, in main
    model = run_e3nn_to_cueq(copy.deepcopy(model))
  File "HOME/envs/mace-from-git/lib/python3.10/site-packages/mace/cli/convert_e3nn_cueq.py", line 191, in run
    config = extract_config_mace_model(source_model)
  File "HOME/envs/mace-from-git/lib/python3.10/site-packages/mace/tools/scripts_utils.py", line 312, in extract_config_mace_model
    "radial_MLP": model.interactions[0].conv_tp_weights.hs[1:-1],
  File "HOME/envs/mace-from-git/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1962, in __getattr__
    raise AttributeError(
AttributeError: 'RadialMLP' object has no attribute 'hs'
```

Additionally, if I try to convert the `MACE-omol-0-extra-large-1024.model` this produces a `mace-lammps.pt` file using the command:

```
python -m mace.cli.create_lammps_model MACE-omol-0-extra-large-1024.model --format mliap
```

However, when I try and run this model, I get a core dump in LAMMPS.  I attached my LAMMPS input file (input_lmp.txt) and output (job_output_2333.log) here.

[job_output_2333.log](https://github.com/user-attachments/files/22626527/job_output_2333.log)

[input_lmp.txt](https://github.com/user-attachments/files/22626532/input_lmp.txt)

Finally, I note that I wasn't able to convert either the `MACE-omol-0-extra-large-1024.model` nor the `mace-omol-0-extra-large-4M.model` using `--format libtorch`. The error after using the `--format libtorch` option was as follows:

```
Traceback (most recent call last):
  File "HOME/psi4conda/envs/mace-from-git/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "HOME/psi4conda/envs/mace-from-git/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "HOME/psi4conda/envs/mace-from-git/lib/python3.10/site-packages/mace/cli/create_lammps_model.py", line 114, in <module>
    main()
  File "HOME/psi4conda/envs/mace-from-git/lib/python3.10/site-packages/mace/cli/create_lammps_model.py", line 109, in main
    lammps_model_compiled = jit.compile(lammps_model)
  File "HOME/psi4conda/envs/mace-from-git/lib/python3.10/site-packages/e3nn/util/jit.py", line 99, in compile
    compile(
  File "HOME/psi4conda/envs/mace-from-git/lib/python3.10/site-packages/e3nn/util/jit.py", line 111, in compile
    mod = torch.jit.script(mod, **script_options)
  File "HOME/psi4conda/envs/mace-from-git/lib/python3.10/site-packages/torch/jit/_script.py", line 1443, in script
    ret = _script_impl(
  File "HOME/psi4conda/envs/mace-from-git/lib/python3.10/site-packages/torch/jit/_script.py", line 1152, in _script_impl
    return torch.jit._recursive.create_script_module(
  File "HOME/psi4conda/envs/mace-from-git/lib/python3.10/site-packages/torch/jit/_recursive.py", line 557, in create_script_module
    return create_script_module_impl(nn_module, concrete_type, stubs_fn)
  File "HOME/psi4conda/envs/mace-from-git/lib/python3.10/site-packages/torch/jit/_recursive.py", line 626, in create_script_module_impl
    script_module = torch.jit.RecursiveScriptModule._construct(cpp_module, init_fn)
  File "HOME/psi4conda/envs/mace-from-git/lib/python3.10/site-packages/torch/jit/_script.py", line 653, in _construct
    init_fn(script_module)
  File "HOME/psi4conda/envs/mace-from-git/lib/python3.10/site-packages/torch/jit/_recursive.py", line 602, in init_fn
    scripted = create_script_module_impl(
  File "HOME/psi4conda/envs/mace-from-git/lib/python3.10/site-packages/torch/jit/_recursive.py", line 630, in create_script_module_impl
    create_methods_and_properties_from_stubs(
  File "HOME/psi4conda/envs/mace-from-git/lib/python3.10/site-packages/torch/jit/_recursive.py", line 466, in create_methods_and_properties_from_stubs
    concrete_type._create_methods_and_properties(
RuntimeError: 
Module 'GenericJointEmbedding' has no attribute 'specs' (This attribute exists on the Python module, but we failed to convert Python type: 'dict' to a TorchScript type. Dictionary inputs to traced functions must have consistent type. Found str and int. Its type was inferred; try adding a type annotation for the attribute.):
  File "HOME/psi4conda/envs/mace-from-git/lib/python3.10/site-packages/mace/modules/embeddings.py", line 60
        """
        embs = []
        for name, spec in self.specs.items():
                          ~~~~~~~~~~ <--- HERE
            feat = features[name]
            if spec["per"] == "graph":
```

**Comment by ilyes319** [comment]
Both of these should be solved in the MACE develop branch, can you make sure to check your mace version is 0.3.15. Can you do a pip list?

**Comment by LucaBrugnoli** [comment]
Thanks, I was able to solve my issue by updating the develop branch to the version 0.3.15 and by running the conversion using the module entry point instead of the script create_lammps_model.py: 
`python -m mace.cli.create_lammps_model  "$MODEL"  --head omat_pbe  --format mliap`

**Comment by angela-oti** [comment]
My MACE version is 0.3.15 from `pip list`, and I confirmed I installed from the develop branch of mace.

[mace-env.txt](https://github.com/user-attachments/files/22637707/mace-env.txt)

 I still get the error when running `python -m mace.cli.create_lammps_model mace-omol-0-extra-large-4M.model --head omol --format mliap` . Is it possible that the issue (at least on my end) is to do with the `omol` format? 

Note that this command does work for MACE-omol-0-extra-large-1024.model
